baseurl = "https://ianmcxa.github.io"
title = "Ian Mcxa"
copyright = "Copyright (c) 2018, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "Ian Mcxa"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "About"
  weight = -115
  identifier = "about"
  url = "/about"

[params.meta]
  keywords = "blog, tech"
  description = "personal blog, tech, computer networking, computer security"

[params]
  github = "ianmcxa"
  gitlab = "ianmcxa"
  email = "ianmcxa@tutanota.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
